# Generated by Django 4.1.5 on 2023-01-25 05:45

from django.db import migrations, models
import django.db.models.deletion
import firmware.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssociatedName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('base_url', models.CharField(max_length=200, unique=True)),
                ('extra_path', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscribedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('send_no_updates_found', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=200)),
                ('download_page', models.CharField(blank=True, max_length=200)),
                ('download_url', models.CharField(blank=True, max_length=200)),
                ('local_file', models.FileField(blank=True, max_length=200, null=True, upload_to=firmware.models.upload_location)),
                ('date_last_seen', models.DateTimeField(null=True)),
                ('read_me', models.TextField(blank=True)),
                ('read_me_path', models.CharField(blank=True, default='Readme.txt', max_length=200)),
                ('hotfix', models.BooleanField(default=False)),
                ('fgs', models.ManyToManyField(blank=True, to='firmware.fg')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discontinued', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('associated_names', models.ManyToManyField(to='firmware.associatedname')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firmware.brand')),
                ('fgs', models.ManyToManyField(to='firmware.fg')),
            ],
        ),
    ]
