# Generated by Django 4.1.5 on 2023-01-30 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmware', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='associated_names',
            field=models.ManyToManyField(blank=True, to='firmware.associatedname'),
        ),
    ]
