# Generated by Django 4.1.5 on 2023-02-07 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firmware', '0003_subscribeduser_activated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribeduser',
            old_name='activated',
            new_name='is_active',
        ),
    ]
