# Generated by Django 4.1.5 on 2023-02-08 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firmware', '0004_rename_activated_subscribeduser_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscribedUser',
        ),
    ]
