# Generated by Django 4.1.5 on 2023-03-07 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmware', '0006_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='send_email_even_if_none_found',
            field=models.BooleanField(default=False),
        ),
    ]
