# Generated by Django 4.1.5 on 2023-05-24 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmware', '0007_subscriber_send_email_even_if_none_found'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='created',
            field=models.DateTimeField(null=True),
        ),
    ]
