# Generated by Django 4.1.5 on 2023-05-24 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmware', '0008_version_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
