# Generated by Django 4.1.5 on 2023-09-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmware', '0011_product_store_firmware_versions_locally'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='do_not_download',
            field=models.BooleanField(default=False),
        ),
    ]
